# Generated by Django 2.1.3 on 2018-11-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_alumno', models.CharField(max_length=40)),
                ('apellidos_alumno', models.CharField(max_length=40)),
                ('edad_alumno', models.IntegerField(blank=True, null=True)),
                ('curso_alumno', models.CharField(max_length=3)),
                ('peso_alumno', models.IntegerField(blank=True, null=True)),
                ('talla_alumno', models.IntegerField(blank=True, null=True)),
                ('perimetro_cintura_alumno', models.IntegerField(blank=True, null=True)),
                ('fuerza_prensil_izquierda_alumno', models.IntegerField(blank=True, null=True)),
                ('fuerza_prensil_derecha_alumno', models.IntegerField(blank=True, null=True)),
                ('imc_alumno', models.DecimalField(decimal_places=2, max_digits=4)),
                ('categoria_imc_alumno', models.CharField(max_length=40)),
            ],
        ),
    ]
